# Numpy array quiz

## Question 1

What is the result of the following code?

```python
    import numpy as np
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    c = a + b
    print(c)
```

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


[5 7 9]

## Question 2

Create a numpy array of 10 zeros. and reshape it to (2, 5)

In [2]:
import numpy as np
arr = np.zeros(10)
arr = arr.reshape(2,5)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Question 3

Find Mean, Mode, Median, Standard Deviation of the following data

In [13]:
import numpy as np
from scipy import stats,ndimage
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
data = np.array(data)

print(f"Mean {stats.hmean(data):.4}")
print(f"Mode {stats.mode(a = data,axis=0,nan_policy='propagate', keepdims = False)}")
print(f"Median {ndimage.median(data)}")
print(f"sDEv {stats.gstd(data):.4}")

Mean 5.559
Mode ModeResult(mode=1, count=1)
Median 10.5
sDEv 2.254


## Question 4

create a 6x6 numpy array with random values and find the min and max values

In [26]:
import numpy as np
import random
arr = np.array([
    [
        list(int(random.randint(1,100)) for _ in range(6))
    ] for _ in range(6)
])
print(arr)
print(f"Max = {np.max(arr)}")
print(f"Min = {np.min(arr)}")

[[[18 49 57 94 80 56]]

 [[52 19 26 72 74 26]]

 [[88 32 94 79 62 97]]

 [[73  7 47 21 28 80]]

 [[20 42  4 38 25 82]]

 [[72 40 59 46 28 92]]]
Max = 97
Min = 4


## Question 5

create a 3D numpy array and reshape it to 2D

In [28]:
import numpy as np
import random
arr = np.array([
    [
        list(int(random.randint(1,100)) for _ in range(3))
    ] for _ in range(2)
])
arr1 = arr.reshape(2,3)
print(f"from {arr.ndim}D tp {arr1.ndim}D")

from 3D tp 2D


## Question 6

create 1D array from this data

```python
    data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

In [32]:
import numpy 
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
data = numpy.array(data)
data = data.reshape(9)
print(f"The dimension of {data} is {data.ndim}")

The dimension of [1 2 3 4 5 6 7 8 9] is 1
