# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for
fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier
transforms, basic linear algebra, basic statistical operations, random simulation and much more.


In [1]:
import numpy as np #import the numpy

-  #### ndarray.ndim
the number of axes (dimensions) of the array.
- #### ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a
matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number
of axes, ndim.
- #### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.
- #### ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python
types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some
examples.
- #### ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize
8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.
itemsize.
- #### ndarray.data
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we
will access the elements in an array using indexing facilities.

In [2]:
david_mark = np.array([
    [90,98,87,85],
    [87,85,86,87],
    [84,75,86,95]
])
print(david_mark)

[[90 98 87 85]
 [87 85 86 87]
 [84 75 86 95]]


In [3]:
print(david_mark.view())

[[90 98 87 85]
 [87 85 86 87]
 [84 75 86 95]]


In [4]:
print(david_mark.base)

None


In [5]:
print(david_mark.shape)

(3, 4)


In [6]:
print(david_mark.ndim)

2


In [7]:
print(david_mark.size)

12


In [8]:
print(david_mark.itemsize)

4


In [13]:
print(david_mark.itemset)

<built-in method itemset of numpy.ndarray object at 0x000001C1D5CEA310>


##### Reshaping arrays

consider a one dimensional array to be reshaped.
Make sure that reshaping is posibble


In [14]:
arr = np.array(
    [i+1 for i in range(12)]
)#1d array

all arrays must contain the same number of elements for example 
the array above of 12 can be reshaped into
2,3,4,6 dimension arrays

In [15]:
print(arr)
arr = arr.reshape(4,3)# reshape to 4 arrays of 3 elements ie(4*3) = 12
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr = np.array(
    [i+1 for i in range(12)]
)#1d array
print(arr)
arr = arr.reshape(2,6)# reshape to 4 arrays of 3 elements ie(2*6) = 12
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
"""arr = np.array(
    [i+1 for i in range(12)]
)#1d array
print(arr)"""
arr = arr.reshape(2,3,2)# reshape to 4 arrays of 3 elements ie(2*3*2) = 12
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
arr = np.array(
    [i+1 for i in range(12)]
)#1d array
print(arr)
arr = arr.reshape(3,4,1)# reshape to 4 arrays of 3 elements ie(2*3*2) = 12
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


Reshape works on all numpy array.
It only caters for the length and elements in the array